name: whazlansaja
description: "UAS Mobile 2 bersama azlansaja"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.4.3
  # sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/gambar_dosen/
